export { FaSlackHash,FaUser,FaFacebookSquare, FaCoins, FaUserEdit, FaTimes } from 'react-icons/fa'
export { TbDiscount2 } from 'react-icons/tb'
export { BsPencilSquare,BsBookmarkStarFill,BsCheckAll,BsThreeDots, BsFillPauseFill, BsPlayFill } from 'react-icons/bs'
export { AiTwotoneFire,AiOutlineInstagram,AiOutlineLoading3Quarters } from 'react-icons/ai'
export { ImHome } from 'react-icons/im'
export { HiLocationMarker, HiViewGrid, HiOutlineMail, HiOutlineInformationCircle } from 'react-icons/hi'
export { SiTiktok } from 'react-icons/si'
export { RiCopyrightLine } from 'react-icons/ri'
export { BiPowerOff, BiSearch, BiCheckShield } from 'react-icons/bi'
export { GrMapLocation } from 'react-icons/gr'
export { TiLocationArrowOutline } from 'react-icons/ti'
export { GrSearchAdvanced } from 'react-icons/gr'